# Generated by Django 5.2.15 on 2026-06-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Document File')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Extracted Text')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='User Question')),
                ('answer', models.TextField(verbose_name='System Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Asked')),
            ],
            options={
                'verbose_name': 'QA History',
                'verbose_name_plural': 'QA Histories',
            },
        ),
    ]
