# Generated by Django 5.2.15 on 2026-06-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qahistory',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='System Answer'),
        ),
    ]
